apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
spec:
  selector:
    matchLabels:
      app: mongo-statefulset
      group: auth
      type: backend
  serviceName: mongo-statefulset-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-statefulset
        group: auth
        type: backend
    spec:
      volumes: 
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-persistent-volume-claim
      containers:
      - name: mongo-statefulset
        image: localhost:5001/mongo:6.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data