apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-volume-claim
spec:
  resources:
    requests:
      storage: 5G
  volumeName: mongo-persistent-volume
  storageClassName: slow
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
