apiVersion: v1
kind: Service
metadata:
  name: mongo-statefulset-service
  labels:
    app: mongo-statefulset-service
    group: auth
    type: backend
spec:
  selector:
      app: mongo-statefulset-service
      group: auth
      type: backend
  ports:
  - port: 27017
    targetPort: 27017
