apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-persistent-volume
spec:
  capacity:
    storage: 10G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
    - rw
  nfs:
    path: /nfs
    server: 192.168.1.57
